repos:
  - repo: local
    hooks:
      - id: linter
        name: linter
        entry: poetry run ruff . && black --check . --diff && isort --check . -diff
        language: system
        types: [python]
